# 1. Import libraries

In [ ]:
import numpy as np 
import pandas as pd
import seaborn as sns
import pandasql as ps 
import matplotlib.pyplot as plt
import re
import plotly.graph_objs as go
from matplotlib import colors 
from wordcloud import WordCloud
%matplotlib inline

# 2. Data Prepration

In [ ]:
df = pd.read_csv("alldata.csv") 
df.head(15)

In [ ]:
df.info()

This dataset contains 6953 rows with 5 columns: Position, Company, Job Description, Review, and Location

# 3. Data Cleaning

In [ ]:
# Check if there are any null values in the data
print(df.isnull().any())

In [ ]:
df.isnull().sum()

In [ ]:
# Drop column Review from the data
df.drop(columns = 'reviews', inplace = True)

In [ ]:
# Remove the rest of the rows containing null value
df.drop(index = df[df['position'].isnull()].index, inplace = True)
df.isnull().any()

In [ ]:
# Add new column 

df['location'] = df.location.apply(lambda x: re.sub('\d*','',str(x)))
df['city'] = df.location.apply(lambda x: x.split(',')[0].strip())
df['state'] = df.location.apply(lambda x: x.split(',')[1].strip())
df['location'] = df['city']+ ', ' + df['state']
df.head()

# 4. Exploratory Data Analysis

# In this section, we will answer the following questions:

1. What is the is the most common job to appear when searching for 'Data Science'?
2. Which company hire the most Data Science job?
3. From the data, which cities hire the most?

In [ ]:
df['location'].nunique()

In [ ]:
print(df['position'].value_counts())

**20 most listed occupations in Data Science field**

In [ ]:
# the 20 most listed occupations in Data Science field

for i, value in enumerate(df.position.unique()): 
    print(i+1,". occupations is ",value)

In [ ]:
# List first 20 most listed positions
df['position'].value_counts()[:20]

In [ ]:
df['position'].value_counts().head(25).plot.bar()

In [ ]:
company = df.groupby(['company']).count().sort_values('position').tail(20)

company['position'].plot(kind='barh',figsize = (10,5))
plt.xlabel('Count', size = 12)
plt.ylabel('')
plt.yticks(size = 10)
plt.xticks(size = 10)
plt.title('Number of Positions by Companies (Top 20)', size = 20)
plt.show()

In [ ]:
plt.figure(figsize=(15,7.5)) 


color_blind_palette = ["#DC267F", "#785EF0", "#648FFF", "#FE6100", "#FFB000", "#E80E8D", "#2E8766", "#95ABAC", "#65B925", "#906A42", "#C4D537", "#344A52", "#6C6E06", "#1C4DD2", "#216E00", "#2E03E5", "#A94424", "#7F6EA9", "#9B8453", "#380721"]

most_listed_occupations = sns.barplot(x=df['position'].value_counts().head(20).index,
                                      y=df['position'].value_counts().head(20).values, palette=color_blind_palette)

plt.xticks(rotation='vertical') #text rotation on x axis for readability
plt.xlabel('position', fontsize=12.5)
plt.ylabel('Count', rotation=0, ha='right', fontsize=12.5)
plt.figtext(.5,.9,"20 most listed occupations in Data Science field", fontsize=20, fontweight='bold', fontname='helvetica', ha='center') #formatted title

for patch in most_listed_occupations.patches:
             most_listed_occupations.annotate("%.0f" % patch.get_height(), (patch.get_x() + patch.get_width() / 2., patch.get_height()),
                 ha='center', va='center', fontsize=10, color='black', xytext=(0, 5),
                 textcoords='offset points')
plt.show()

**20 jobs with highest cities in top rated companies**

In [ ]:
df_task_highest_salary_top_comp = """SELECT Position, Company, location 
             FROM df 
             GROUP BY Position
             ORDER BY location DESC
             LIMIT 20"""
ps.sqldf(df_task_highest_salary_top_comp)

In [ ]:
plt.figure(figsize=(15,7.5)) 


color_blind_palette = ["#DC267F", "#785EF0", "#648FFF", "#FE6100", "#FFB000", "#E80E8D", "#2E8766", "#95ABAC", "#65B925", "#906A42", "#C4D537", "#344A52", "#6C6E06", "#1C4DD2", "#216E00", "#2E03E5", "#A94424", "#7F6EA9", "#9B8453", "#380721"]

most_listed_occupations = sns.barplot(x=df['location'].value_counts().head(20).index,
                                      y=df['location'].value_counts().head(20).values, palette=color_blind_palette)

plt.xticks(rotation='vertical') #text rotation on x axis for readability
plt.xlabel('location', fontsize=12.5)
plt.ylabel('Count', rotation=0, ha='right', fontsize=12.5)
plt.figtext(.5,.9,"20 most cities of Data Science field", fontsize=20, fontweight='bold', fontname='helvetica', ha='center') #formatted title

for patch in most_listed_occupations.patches:
             most_listed_occupations.annotate("%.0f" % patch.get_height(), (patch.get_x() + patch.get_width() / 2., patch.get_height()),
                 ha='center', va='center', fontsize=10, color='black', xytext=(0, 5),
                 textcoords='offset points')
plt.show()

In [ ]:
city = df.groupby(['location']).count().sort_values('position').tail(20)

city['position'].plot(kind='barh',figsize = (10,5))
plt.xlabel('Count', size = 12)
plt.ylabel('')
plt.yticks(size = 10)
plt.xticks(size = 10)
plt.title('Number of Positions by Cities (Top 20)', size = 20)
plt.show()

In [ ]:
plt.figure(figsize=(15,7.5)) 


color_blind_palette = ["#DC267F", "#785EF0", "#648FFF", "#FE6100", "#FFB000", "#E80E8D", "#2E8766", "#95ABAC", "#65B925", "#906A42", "#C4D537", "#344A52", "#6C6E06", "#1C4DD2", "#216E00", "#2E03E5", "#A94424", "#7F6EA9", "#9B8453", "#380721"]

most_listed_occupations = sns.barplot(x=df['company'].value_counts().head(20).index,
                                      y=df['company'].value_counts().head(20).values, palette=color_blind_palette)

plt.xticks(rotation='vertical') #text rotation on x axis for readability
plt.xlabel('company', fontsize=12.5)
plt.ylabel('Count', rotation=0, ha='right', fontsize=12.5)
plt.figtext(.5,.9,"20 most companies in Data Science field", fontsize=20, fontweight='bold', fontname='helvetica', ha='center') #formatted title

for patch in most_listed_occupations.patches:
             most_listed_occupations.annotate("%.0f" % patch.get_height(), (patch.get_x() + patch.get_width() / 2., patch.get_height()),
                 ha='center', va='center', fontsize=10, color='black', xytext=(0, 5),
                 textcoords='offset points')
plt.show()

In [ ]:
dfd1 = df[df['position'] == 'Data Scientist']
dfd2 = df[df['position'] == 'Senior Data Scientist']
dfd3 = df[df['position'] == 'Research Analyst']
dfd4 = df[df['position'] == 'Data Engineer']

redf1 = dfd1["location"].value_counts()[:10].reset_index()
redf2 = dfd2['location'].value_counts()[:10].reset_index()
redf3 = dfd3['location'].value_counts()[:10].reset_index()
redf4 = dfd4['location'].value_counts()[:10].reset_index()

fig = go.Figure()

fig.add_trace(go.Bar(
    x=redf1['location'],
    y=redf1['location'],  
    marker=dict(color='Tomato'),
    name='Data Scientist'
))

fig.add_trace(go.Bar(
    x=redf2['location'],
    y=redf2['location'], 
    name='Senior Data Scientist',
    marker=dict(color='LightCoral')
))

fig.add_trace(go.Bar(
    x=redf3['location'],
    y=redf3['location'], 
    name='Research Analyst',
    marker=dict(color='SteelBlue')
))

fig.add_trace(go.Bar(
    x=redf4['location'],
    y=redf4['location'],  
    name='Data Engineer',
    marker=dict(color='CadetBlue')
))


fig.show()

In [ ]:
positions_text = " ".join(df['company'].dropna().to_list())
wordcloud = WordCloud(max_font_size=50, max_words=100, background_color="white").generate(positions_text)
  
# plot the WordCloud image                        
plt.imshow(wordcloud) 
plt.axis("off") 
plt.tight_layout(pad = 0) 
  
plt.show()